### ISSUE TITLE
Create collection related code for services feature

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#104]
Create schema, collection, publication and privileges for services collection

Definition of done
---
* [x] Services collection exists.
* [x] Services schema exists.
  * [x] Services schema contains field defined in requirements document.
  * [x] Schema is attached to the services collection.
* [x] Services publications exist.
  * [x] All organization services publication exists
  * [x] Single service publication exists

# Resources
See the [Service summary view](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/docs/requirements.md#service-summary-view-registered-user) section of the requirements document for some details about the direction of this feature.

**Comment by bajiat** [comment]
@brylie Would you be interested in this?

**Comment by brylie** [comment]
Opened PR with WIP.

**Comment by bajiat** [comment]
@brylie open a separate issue on permissions and roles
