### ISSUE TITLE
Define API for services

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#110]
Create REST API endpoints for services collection (organization services publication, department services publication, single service publication).

Definition of done
---
* [x] REST routes have been added for services collection.
  * [x] organization services 
  * [x] department services
  * [x] single service
* [ ] REST routes have access control.
* [x] REST routes are included in Swagger documentation.

**Comment by jykae** [comment]
Interested

**Comment by jykae** [comment]
Depending on Services collection #104
