### ISSUE TITLE
Study the underlying technologies for Wikimedia dashboard

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#116]
Study the Wikimedia dashboard at http://korma.wmflabs.org/browser/ that shows the health of a single open source project and the underlying toolkit that have integrations with Github and other sources.

Definition of done
---
* [x] Set up an instance and try to analyse the health of apinf.io project, primarily through the data available in Github
* [ ] Set up the charting component to display the data
* [ ] Try to agregrate data from two repositories, e.g. api-umbrella-dashboard and meteor-api-umbrella

**Comment by brylie** [comment]
I have looked into the utility library related to the dashboard sites. The utility is called Perceval, and runs via command line. I have generated two Perceval output files based on our project, first by analyzing our Github metadata and second by analyzing out git repository directly:

* [dipor-dashboard github-output.txt](https://github.com/Digipalvelutehdas/dipor-dashboard/files/185890/github-output.txt)
* [dipor-dashboard git-output.txt](https://github.com/Digipalvelutehdas/dipor-dashboard/files/185891/git-output.txt)

**Comment by brylie** [comment]
I opened a [support request](https://github.com/grimoirelab/perceval/issues/28) asking for assistance parsing the outputted files to valid JSON.
