### ISSUE TITLE
Create a (sub)view(s) for charting service data

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#142]
Using Admin LTE semantics, create (sub)view(s) for service data visualizations for the service owner dashboard. Create the required subscription(s) as well.

Definition of done
---
* [ ] Place statistics from [Github repository statistics](https://developer.github.com/v3/repos/statistics) into the subview.
  * [ ] [Contributors](https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts)
  * [ ] [Commits over time](https://developer.github.com/v3/repos/statistics/#get-the-last-year-of-commit-activity-data)

**Comment by brylie** [comment]
@frenchbread would you consider taking this task?

**Comment by frenchbread** [comment]
I am on it!

**Comment by brylie** [comment]
@frenchbread if you haven't already, check out the [node-github](https://www.npmjs.com/package/node-github) package to get commits over time for a repository. 

We have a method in our Github Viewer project, called `getCommitActivity`. The following code will suffice for a line or bar graph of commits over time:

```js
const commitActivity = Meteor.call("getCommitActivity", "Digipalvelutehdas", "dipor-dashboard");

console.log(commitActivity);
```

The activity data is structured as so:

```json
[
  { 
    days: [ 
      0,
      30,
       5,
       7,
       9,
       0,
       0 
    ],
    total: 51,
    week: 1458432000 
  },
  { 
    days: [ 
      0,
      0,
      0,
      7,
      26,
      10,
      0
    ],
    total: 43,
    week: 1459036800 
  },
  {
    days: [
      0,
      26,
      0,
      0,
      0,
      0,
      0 
    ],
    total: 26,
    week: 1459641600 
  } 
]
```

**Comment by brylie** [comment]
Also, please consider using a chart from the [NVD3 library](http://nvd3-community.github.io/nvd3/examples/site.html). After exploring Dimple, Chart.js, DC.js, and NVD3, we concluded that NVD3 gave us the right combination of features and usability for the current phase of this project.

**Comment by frenchbread** [comment]
Ok, thanks for info!

**Comment by bajiat** [comment]
@frenchbread What is the status of the task?

**Comment by frenchbread** [comment]
@bajiat Have not started it yet.

**Comment by brylie** [comment]
@frenchbread please merge your work in progress with the work Illya and I did over the weekend. The only remaining task is to show contributors.

**Comment by brylie** [comment]
@frenchbread, @elnzv and I made a Github commits over time chart during the weekend hack-day. Please add your efforts to that branch. I opened a pull request (#204) for your convenience.

**Comment by frenchbread** [comment]
I added contributors list to a table. Yet, it gives an error. Will fix it tomorrow :)

**Comment by frenchbread** [comment]
Contributors feature is implemented. Please review #204
