### ISSUE TITLE
Create a scheduling function for getting commit data for a service

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#144]
Create method(s) for fetching data from Github. Add a schedule to run the method periodically. As a minimum, we need the following data: commits.

Definition of done
---
* [x] Method exists for fetching all commit data from Github repository.
* [x] Method takes as a argument a specified timeframe.
* [x] When a service is added to portal, schedule starts to run periodically after initial pull.

**Comment by bajiat** [comment]
@Alapan @ashakunt Could this be an interesting task for Aseem since @jykae is not available for this task?

**Comment by brylie** [comment]
@frenchbread or @Alapan, would you please self-assign this task?

**Comment by frenchbread** [comment]
Self-assigned.
