### ISSUE TITLE
Create language switching option

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#147]
Create the functionality that allows users to switch between UI languages.

As an end-user I want to see UI texts on my native language.

# Definition of done
- [ ] Language switcher exists in navigation menu.
- [ ] Language switcher contains languages that have been translated and imported to project.
- [ ] When user changes the language, all UI texts are changed reactively.

**Comment by Nazarah** [comment]
English
Suomi
Svenska (Swedish) ?????

**Comment by Nazarah** [comment]
Make sure the changing option appear in top menu, rather than in user profile or settings.

**Comment by bajiat** [comment]
The language options should (automatically) correspond to what are the languages available in localisation files. Currently that is only Finnish and English, Swedish is an open issue.
