### ISSUE TITLE
Select and install CSS framework

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#15]
_From @bajiat on February 19, 2016 12:9_

Choose and install a CSS framework to carry project forward. 

### Considerations include
* Meteor packaging and integration with other common packages, e.g. autoform and accounts UI
* Team familiarity
* Documentation

Definition of done
--- 
* [x] Study the alternatives quickly
* [x] Make informed recommendation in writing to the team (details in this issue)
* [x] Get team approval
* [x] Install package

_Copied from original issue: Dipor/platform#1_

**Comment by bajiat** [comment]
@elnzv Would you be interested in selecting the CSS framework?

**Comment by elnzv** [comment]
Alternatives:
- [Foundation](https://atmospherejs.com/ewall/foundation)
- [Semantic UI ](https://atmospherejs.com/semantic/ui-css)

These two are good, but I propose to use [Bootstrap](https://atmospherejs.com/twbs/bootstrap):
- our team is already familiar with it, so saves us time,
- Bootstrap is really powerful framework with many features and full of examples,
- also there many other common packages, e.g. autoform and accounts UI,
- finally, [Bootstrap 4](http://v4-alpha.getbootstrap.com/) is coming;

@Digipalvelutehdas/dipor-team, do you approve Bootstrap?

**Comment by brylie** [comment]
:+1:

**Comment by bajiat** [comment]
+1 for Bootstrap, because dev team is already familiar with it

**Comment by frenchbread** [comment]
Yea, let's stick with Bootstrap.
