### ISSUE TITLE
Create portal settings view and collection

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#150]
Create collection, schema, publication, subscription and view for portal settings, which should include as a minimum Github API key.

# Definition of done
- [x]  `Settings` collection exists
- [x] Settings schema exists
  - [x] schema contains Github API authentication field(s) (e.g. OAuth)
- [x] Settings publication exists
  - [x] publication checks for user permission (i.e. superuser) before returning data
- [x] Settings view exists
  - [x] view shows Github authentication field(s)
  - [x] view contains settings form
  - [x] settings are updated when form submits
- [x] Settings route exists
  - [x] route renders settings page
  - [x] route checks for superuser permission
  - [x] route returns access denied for non-superuser accounts

**Comment by brylie** [comment]
@elnzv would you please take this task?
