### ISSUE TITLE
Store Github issue data for a service

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#155]
Create collection, schema and publication for the following Github issues for a service. 

Blocks #144.

Definition of done
---
* [x] Collection for Github issues exists.
* [x] Schema for Github issues exists.
* [x] Schema mirrors [Github API structure](https://developer.github.com/v3/issues)
* [x] When adding a Github repository to a service, all issues are pulled to the collection.
* [x] Publication for Github issues exists.

**Comment by brylie** [comment]
@frenchbread would you please consider taking the lead on this task?

**Comment by frenchbread** [comment]
Yes.

**Comment by brylie** [comment]
@frenchbread,  would you like to meet to discuss your sprint tasks?

**Comment by frenchbread** [comment]
@brylie No, It's ok. I'll stick to definition of done for now.

**Comment by bajiat** [comment]
@frenchbread What is the status? Did you know that Alapan is working on a related task on syncing / scheduling data Github issues?

**Comment by frenchbread** [comment]
Related RP - #202. Branch: [`feature/github-issue-data-for-service`](https://github.com/Digipalvelutehdas/dipor-dashboard/tree/feature/github-issue-data-for-service)

**Comment by frenchbread** [comment]
#202  Ready for review. @Digipalvelutehdas/dipor-team
