### ISSUE TITLE
Create a scheduling function for getting issue data for a service

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#156]
Create method(s) for fetching issue data from Github. Add a schedule to run the method periodically.

# Goal
Make sure our local collection of Github issues stays in sync with Github as issues are added, updated, and closed. This means at any given time, our collection will have the same information as Github. E.g.

- correct details for all issues
  - open date
  - update date
  - closed date
  - Issue title
  - Labels

We can ask Github for ALL issues every time this function runs, but that may prove to be inefficient. Instead, we want to ask Github for only issues that have changed since a given time, regardless of whether they are still open.

# Definition of done

* [x] Method exists for fetching all issue data from Github repository.
* [x] Method takes as a argument a specified timeframe.
* [x] When a service is added to portal, schedule starts to run periodically after initial pull.
* [ ] *All* issues having recent changes are synchronized when scheduling function runs
  - This means that we only receive issues that have changed
  - changed issues can mean they were closed since last run

**Comment by bajiat** [comment]
@Alapan @ashakunt Could this be an interesting task for Aseem since @jykae is not available for this task? There is an example in Apinf about scheduling database updates from Umbrella.

**Comment by bajiat** [comment]
@Alapan @ashakunt Comment from @brylie: It is enough for now, if the scheduling function just posts/echos "hello world" and service name for each available service instead of fetching data from Github, Assign either #156 or #144 to yourself, no need to work on both at this stage, because the is blocked by other data fetching tasks. We would also like to suggest task #168 to you.

**Comment by ashakunt** [comment]
Does this scheduling function have to be running offline? Or only when anyone is logged in (e.g. fetch only the data that is interesting to me?). 

In the second case, IMHO, setInterval can be used to fetch data. 

@brylie what option are we looking at here?

**Comment by brylie** [comment]
It probably needs to run on the server, so will not be tied to a user session.

**Comment by brylie** [comment]
There is a Meteor package called [Synced Cron](https://github.com/percolatestudio/meteor-synced-cron) that is a good candidate for this feature.

**Comment by brylie** [comment]
In general, Meteor will push available data to users in real-time, via DDP. This task is related to fetching data from a REST API periodically, so that it will automatically propagate to users.

**Comment by Alapan** [comment]
Started work on it today.

**Comment by Alapan** [comment]
I have written a method which runs the Github API call as a cron job. The method seems to work properly on my Meteor shell and browser console. On the client side, in `Autoform.onSuccess()`, I have placed a commented-out call to that method. The job, for now, is scheduled to run every 2 hours.

**Comment by brylie** [comment]
@Alapan what is the status of this task? Would you like to meet today in Rocket.Chat?

**Comment by brylie** [comment]
@Alapan I have been reflecting on the pull request we merged yesterday. It seems like the method we used may not work to meet the goal of this task. Lets work together to make sure we are taking the right approach here.

**Comment by brylie** [comment]
This task is admittedly not easy, but may be one of the more important tasks we currently have.

**Comment by brylie** [comment]
Re-opening, based on discussion with @Alapan. Basically, we need to synchronize *all* issues from Github, but our current code only receives *open* issues. We need all issues so that we can keep track of the date they are closed.
