### ISSUE TITLE
Test Dipor deployment (sprint 3)

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#158]
Go to [Dipor deployment](dashboard.digipalvelutehdas.fi) for release based on sprint 3 and test the available views.

Definition of done
---
* [x] Register into the portal
* [x] Create at least one organization
* [x] Create at least one department
* [x] Create at least one service
* [x] Test inline editing
* [x] Test member management
* [x] Report any problems as issues
  * [x] Describe the test to reproduce the problem
  * [x] List all created issues as a comment to this task

**Comment by ashakunt** [comment]
@saralavanip please take this task.

**Comment by bajiat** [comment]
@jykae can you add a comment here when deployment for sprint 3 release is available. Thanks!

**Comment by saralavanip** [comment]
Testing in progress.
- Version 0.3.0 :  https://dashboard.digipalvelutehdas.fi

**Comment by saralavanip** [comment]
Please find the reported issues below:  

https://github.com/Digipalvelutehdas/dipor-dashboard/issues/167  
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/168
