### ISSUE TITLE
Input field invisible while editing description of an organization

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/dipor-dashboard#167]
Steps:   

1.Visit https://dashboard.digipalvelutehdas.fi    
2.Login  
3.Click on 'Create Organization'    
4.Enter the details:  
    - Enter valid name
    - Enter description  
5.Click on 'Create'  
6.Go to Organization view and select the organization added above  
7.Click on 'Edit'  
8.Delete the text in description field  

Findings:  
- Input field for adding description is invisible
- Default input text 'type your text' is invisible

Operating System:  
- Linux : Ubuntu 14.04.03 LTS (Trusty)

Browser:
- Google Chrome 48.0.2564.103  

Screenshot:      

![edit-org-input -field-invisible](https://cloud.githubusercontent.com/assets/13309358/14276568/06781f02-fb28-11e5-8099-73998b351217.png)

**Comment by frenchbread** [comment]
Created hotfix #169. Please confirm the bug is resolved. Related branch for testing - `hotfix/edit-organiaztion-description-field`
