### ISSUE TITLE
User unable to edit 'Service' status

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/dipor-dashboard#168]
Steps: 

1.Visit https://dashboard.digipalvelutehdas.fi   
2.Login  
3.Create Organization  
4.Go to Organization view and select the organization added above     
5.Create Department  
6.Select the department added above  
7.Add Service  
8.Click on service added above  
9.Click on 'Edit'  and update service status 

Result: User not allowed to edit service status      

Operating system: 
- Linux : Ubuntu 14.04.03 LTS (Trusty)

Web Browsers:
- Google Chrome 48.0.2564.103    

Screenshot:      

![unable-to-edit-servicestatus](https://cloud.githubusercontent.com/assets/13309358/14277773/5c21d97a-fb2d-11e5-8b48-61666af71f26.png)

**Comment by frenchbread** [comment]
Related issue - #154

**Comment by bajiat** [comment]
@alapan Could you take this task?

**Comment by Alapan** [comment]
Started work on this issue.

**Comment by Alapan** [comment]
@brylie I added an X-editable dropdown, but haven't yet figured out how to populate the dropdown options with the allowed values from the Services schema.

**Comment by frenchbread** [comment]
@Alapan Here is probably not the best approach but one that works:

```javascript
const statusAllowedValues = Services.schema._schema.status.allowedValues;

let options = [];

_.each(statusAllowedValues, (value) => {
  options.push({
    text: value,
    value: value
  })
})

$('#service-status').editable({
  type: 'select',
  source: options
});
```

**Comment by Alapan** [comment]
@frenchbread Thank you, that works!!
