### ISSUE TITLE
Create the REST API for Organizations

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#17]
_From @bajiat on February 19, 2016 12:21_

Create REST API endpoints for Organizations collection (all organizations publication, single organization publication).

Definition of done
---
* [x] Quick research about REST packages for Meteor, e.g. Simple REST.
* [x] REST package has been added to project.
* [x] REST routes have been added for organizations collection.
* [x] REST routes have access control.

# Related
Depends on issue #9 

_Copied from original issue: Dipor/platform#14_

**Comment by bajiat** [comment]
To be assigned to frenchbread

**Comment by jykae** [comment]
@frenchbread I would be interested to work on this one as I am now back from sick vacation.

**Comment by frenchbread** [comment]
Ok, feel free @jykae!

**Comment by jykae** [comment]
The beginning of simple REST:

![simplerest](https://cloud.githubusercontent.com/assets/293452/13464078/05f75bf6-e098-11e5-9bd3-a1abab818b7b.png)

**Comment by jykae** [comment]
just clarifying requirements for this task, basic CRUD operations should be probably available for organizations? For API authentication proposing token auth, https://github.com/stubailo/meteor-rest/tree/master/packages/authenticate-user-by-token

**Comment by jykae** [comment]
Current API routes, 

![apiroutes](https://cloud.githubusercontent.com/assets/293452/13492596/a2ac4cdc-e141-11e5-9a7e-c32bc1b6b0e8.png)

Would be good to somehow define also collection CRUD operations /organizations under /api/organizations haven't found way how to do so, as GET method now clashes with organization view route. For publications it's possible to define custom route.

I could also evaluate Restivus package, if it would provide better customization.

**Comment by jykae** [comment]
Opened issue related custom endpoint route for collections: https://github.com/stubailo/meteor-rest/issues/94
