### ISSUE TITLE
Create wireframes for views

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#172]
Create wireframes for organization, department, service view and default views with annotations indicating user permissions. Check also if there are missing views.

Refer to 
* [ requirements document](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/docs/requirements.md)
* [LoFi wireframes](https://github.com/Digipalvelutehdas/dipor-dashboard/tree/develop/docs/Design/LoFiPNGs)

Definition of done
---
* [ ] Wireframes for each of our key views exist: organization, department, service and default views 
* [ ] Wireframes contain information about user permissions for entire view or particular fields.
* [ ] Missing views have been identified.
* [ ] Optionally, organize a workshop for designing or reviewing wireframes.

**Comment by bajiat** [comment]
@elnzv Hi, what is the status of the wireframes? We would like to use the wireframes as a source of info for sprint planning.

**Comment by brylie** [comment]
Added initial wireframe for Organizations template:

![Organizations template](https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/feature/ui-wireframes/docs/Design/wireframes/organizations.png)

Opened PR #201 (work-in-progress)
