### ISSUE TITLE
Add inline editing to organization view

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#18]
_From @bajiat on February 19, 2016 12:16_

One of the user requirements for portal was allowing inline editing instead of having separate page for editing. Study the options for inline editing and make an informed decision based on the study. 

Definition of done
---
* [x] Inline editing framework has been chosen.
* [x] Edit button for organization view exists.
* [x] Clicking edit button enables inline editing for page elements
* [x] Clicking save button saves changes to database.
* [x] Cancel button disables edit more
* [x] Only edit button or save and cancel buttons are available at any given time.
* [x] Edit and save / cancel buttons are available only for administrators.

# Related
Depends on issue #9

# Resources
## Inline editor options
* [MediumEditor](https://yabwe.github.io/medium-editor/)
* [Hallo.js](http://hallojs.org/)

_Copied from original issue: Dipor/platform#10_

**Comment by bajiat** [comment]
To be assigned to frenchbread

**Comment by brylie** [comment]
FWIW, I used the Hallo.js in the [Lean Canvas demo app](https://github.com/Dipor/canvas-app). However, I like that MediumEditor has no dependencies, and seems to have quite a few extensions.

**Comment by frenchbread** [comment]
Tried MediumEditor, looks cool! It also has official [`meteor package`](https://atmospherejs.com/mediumeditor/mediumeditor).

**Comment by brylie** [comment]
Ah, cool. My vote goes for MeteorEditor then :-) :+1:

**Comment by brylie** [comment]
@frenchbread we realized that only organization administrators should be able to edit the organization details, so updated the description. Also, make sure that we save the changes in the collection.

**Comment by frenchbread** [comment]
@brylie Yep, working on it. Have some progress.

How do we deal with permissions if there is no any roles yet?

**Comment by frenchbread** [comment]
Oh, actually this is about writing custom helper..

**Comment by brylie** [comment]
That is part of it, yes. We realized there probably needs to be an 'edit mode' with 'save' and 'cancel' buttons, so that changes can be stored to the collection or reverted.

**Comment by brylie** [comment]
It is up to you whether we go the 'save' and 'edit' button route, or if there is a more elegant solution.

Basically, we need to
*  make sure only authorized users can edit, 
* help users realize the details can be edited via a signifier
* make sure edits are saved to the collection, or reverted if the user cancels somehow

**Comment by frenchbread** [comment]
Created PR #61.
