### ISSUE TITLE
Create organization view

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#19]
_From @bajiat on February 19, 2016 12:14_

Create initial markup for public organization view. Include i18n tags.

Definition of done
---
* [x] Basic organization markup exists, optionally using CSS framework semantics.
* [ ] i18n tags have been included for any UI texts.
* [x] Subscription to Organization publication exists.

_Copied from original issue: Dipor/platform#7_

# Reference
Please see the [requirements document (organization view section)](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/master/docs/requirements.md#organization-view-registered-user-who-is-a-member-of-the-organization-in-question) for our current understanding of the organization view.

# Depends on
* #9
* #13 
* #4

**Comment by bajiat** [comment]
To be assigned to frenchbread after the issue has been migrated to Digipalvelutehdas.

**Comment by frenchbread** [comment]
Waiting for issue #9 to be implemented. Currently blocked.

**Comment by brylie** [comment]
@frenchbread I have added a link to the requirements document description of this view:
https://github.com/Digipalvelutehdas/dipor-dashboard/blob/master/docs/requirements.md#organization-view-registered-user-who-is-a-member-of-the-organization-in-question

**Comment by frenchbread** [comment]
@brylie Ok, thanks.

**Comment by frenchbread** [comment]
Working branch - [`feature/19-organization-view`](https://github.com/Digipalvelutehdas/dipor-dashboard/commits/feature/19-organization-view).
