### ISSUE TITLE
Add feature to allow organization logo upload

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#190]
Our requirements document indicates that organizations will have a logo. Design a UI for adding organization logos and implement the underlying logic/storage.

As a superuser or organization administrator, I want to upload organization logo image so that I can manage my organization's branding.

# Definition of done
- [x] There is an upload UI for organization logo. 
  - [x] UI is accessible for superusers and organization admins.
- [x] When organization logo has been added, it is displayed in relevant templates
  - [x] organization catalog
  - [x] single organization page
  - [x] user can edit logo
- [x] Logo is stored either in file system or in collection.

# Resources
The following package(s) may be useful to implement this feature:

- [meteor-uploads](https://github.com/tomitrescak/meteor-uploads)

**Comment by Nazarah** [comment]
Ask for Jarkko to supply with legit LOGO pngs for organizaiton.
in Case a logo is not available, "No logo is available" text can appear in a rectangle"

**Comment by Nazarah** [comment]
Also consider that if we are using expand collapse panes and somehow those panes represent organizations, should we consider showing the logos there along with organization names.

**Comment by brylie** [comment]
@elnzv what is the status of this task?

**Comment by elnzv** [comment]
@brylie, starting working on this today.

On Tue, 3 May 2016, 12:14 Brylie Christopher Oxley, <
notifications@github.com> wrote:

> @elnzv <https://github.com/elnzv> what is the status of this task?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/Digipalvelutehdas/dipor-dashboard/issues/190#issuecomment-216475182>
>
-- 

Illya Nizyev ~ www.nzv.nz
