### ISSUE TITLE
Ensure chart color palette is accessible for colorblind people

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#191]
In order to ensure that our data visualizations are accessible, we need to consider what colors to use. As a basis for this research, start with the [D3.js 10 categorical color palette(s)](http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d), and determine the accessibility of colors therein.

The D3.js category10 color values, with made up labels, are:

- "blue": #1f77b4
- "orange": #ff7f0e
- "green": #2ca02c
- "red": #d62728
- "violet": #9467bd
- "brown": #8c564b
- "pink": #e377c2
- "grey": #7f7f7f
- "yellow": #bcbd22
- "light blue": #17becf

**Comment by brylie** [comment]
I ran a color test on the D3.js 10 color palette using TinyColor, which is already available in our project. Here is some code to reproduce the test:

```js
var tinycolor = require("tinycolor2")

var red = tinycolor("#d62728");

var green = tinycolor("#2ca02c");

var redBrightness = red.getBrightness();
var greenBrightness = green.getBrightness();

console.log(redBrightness, greenBrightness);
```

**Comment by bajiat** [comment]
Has been tested and can be closed.
