### ISSUE TITLE
Add UI widget for toggling Service visibility

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#192]
When creating or viewing a service, a Product Owner might need to toggle the service visibility. E.g. public/private. Design and add a UI element to toggle the service visibility, at least in two places:

- Add Service form
- View Service page

Also, perform a check on the route to check whether user is authorized to view the service or not. If not authorized, show 403 template.

Blocks #297.

# Definition of done
- [ ] Add service form contains a visibility widget (a field or similar) for setting the service visibility as public or private.
- [ ] View Service page also contains visibility widget for setting the service visibility as public or private.
- [ ] Toggling the visibility widget updates the service visibility field.
- [ ] Route permission check exists for direct service route.
  - [ ] Route permission checks whether the service is public. If service is private, it checks the user permission. If the user is not authorized to view the service, 403 is displayed.

**Comment by Nazarah** [comment]
Make sure the toggle options available only when a user with PO priviledges signs in and visits the page of the service he is the PO of.

**Comment by Nazarah** [comment]
about the 403, we can give a more meaningful message than 403. technical message always don't provide intuitiveness to users.

"You don't have adequate permission to view this service. Please contact Product Owner of this service to obtain the required permission."

**Comment by brylie** [comment]
@bajiat, will you confirm with @kyyberi what the default service visibility status should be? We need to set the default status to 'public' or 'private'.

**Comment by brylie** [comment]
Currently, all services are 'public' by default, since we have not previously added any check(s) for the `visibility` field.

**Comment by brylie** [comment]
Added a service visibility toggle to the "Single Service" page:

![screenshot from 2016-05-09 13-34-04](https://cloud.githubusercontent.com/assets/17307/15110654/ef98fb0c-15ea-11e6-99c6-abf3d67bb100.png)
![screenshot from 2016-05-09 13-34-12](https://cloud.githubusercontent.com/assets/17307/15110653/ef95a06a-15ea-11e6-9320-ee5b259730c1.png)
