### ISSUE TITLE
Add service status as label to each service in Department view

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#196]
In order for people to quickly see service statuses, we can add the status as a label to the Services list in the Department view.

# Definition of done
- [ ] Service status label appears next to each item in Services block in Department.
- [ ] Consider grouping and/or sorting services by status label

**Comment by Nazarah** [comment]
Adding a sample wireframe in design doc. Willgive the link as soon as pull request is accepted.
