### ISSUE TITLE
Allow only superuser(s) to add organizations

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#205]
The requirements document indicates that, initially at least, only superusers should be allowed to add organizations. In our code, the superuser is given the `admin` role. Add a template helper and collection permission check, ensuring that only `admin` users can add organization(s).

# Definition of done
- [x] "Create Organization" button is only visible for administrative users (`admin` role)
- [x] Only users with `admin` role can `insert` documents into the `Organizations` collection

# Reference
The following resources may prove useful to implement this task:

- Meteor Guide - [Roles and Permissions](http://guide.meteor.com/accounts.html#roles-and-permissions) section
- [Meteor Roles](https://github.com/alanning/meteor-roles/blob/master/README.md) documentation

The following code can be used in the template to dynamically show/hide UI elements based on user role:

```html
{{#if isInRole 'admin'}}
  <!-- show "Add organization" button -->
{{/if}}
```

**Comment by brylie** [comment]
@Alapan will you consider taking this issue? I will provide a definition of done shortly. The task involves writing
-  a template helper to hide the "Add organization" button, and 
-an `Organizations` collection allow rule to enforce the permission when inserting a new organization.

**Comment by Alapan** [comment]
@brylie I would like to work on this issue.

**Comment by brylie** [comment]
OK, you are assigned. Would you like to meet to discuss the requirements?

**Comment by Alapan** [comment]
Yes - will we discuss it online or face-to-face?

**Comment by brylie** [comment]
Online is fine. I have updated the definition of done.

**Comment by elnzv** [comment]
@Alapan, I have a task #150, which includes check if user has superuser rights.
Brylie did package to make first user admin - https://atmospherejs.com/brylie/first-user-admin
We can use it in this project as well.

**Comment by brylie** [comment]
Lets fork that package into the Digipalvelutehdas account, so we can collaborate and add improvements.
