### ISSUE TITLE
Create organization catalog

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#211]
Refer to organizations catalog wireframe.

**Comment by brylie** [comment]
@elnzv will you please take this task?

**Comment by elnzv** [comment]
@brylie could you please add definition of done?

**Comment by brylie** [comment]
@elnzv please review the definition of done and wireframe.

**Comment by elnzv** [comment]
@brylie, looks good. Thanks!

**Comment by brylie** [comment]
Jep. Let me know if I have overlooked any crucial details. We can use the definition of done as a general goal.

**Comment by brylie** [comment]
Wow, the definition of done seems to have disappeared.
