### ISSUE TITLE
Create function to add OAuth token to Github requests

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#214]
The NPM Github library can make authenticated API requests, using an OAuth token.  This allows the platform to make more than 60 requests per hour.

As a follow up to the settings page feature (#150), pass the OAuth token to the Github object when the token is available.

# Definition of done
- [x] `Github` initialization checks for OAuth token passed in via `--settings` flag
- [x] If OAuth token is available, Github object uses token for all API requests
- [ ] *Optional* If OAuth token changes, e.g. via settings UI, the Github object is updated with the changed OAuth token

# References
- [NPM Github](https://www.npmjs.com/package/github)
- [npm github authentication options](http://mikedeboer.github.io/node-github/#Client.prototype.authenticate)

**Comment by jykae** [comment]
@elnzv FYI, server method "githubAuthenticate" can be called when Github settings are given in the Settings UI. Returns true on success, false on failure.
