### ISSUE TITLE
Create a chart showing issue counts by tag for a given repository

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#221]
```
As a project owner
I would like to see counts of issues by tag
so that I can quickly see how my project issues are distributed
```

**Comment by brylie** [comment]
@frenchbread would you consider taking this task?

**Comment by frenchbread** [comment]
Should chart for this issue be represented as a "bar chart" or just a list of tags for specific repo and issues count next to it?

**Comment by brylie** [comment]
A bar chart would be nice. E.g. each bar would be a count of issues for a specific tag. That way, we can quickly see which tags have the most issues.

**Comment by brylie** [comment]
@frenchbread check out the updated [NVD3 Examples site](http://nvd3-community.github.io/nvd3/examples/site.html) to find some sample code for the bar chart.

**Comment by brylie** [comment]
Also, please don't make a pie chart :smiley:

**Comment by frenchbread** [comment]
@brylie Ok, thanks!

**Comment by Nazarah** [comment]
Consider when there are chances that  100 labels exist.
How it is going to affect the visualization?

**Comment by Nazarah** [comment]
I'll add a sketch to show how the 2 rows (textual info +charts) are going to appear
