### ISSUE TITLE
Test Dipor deployment (sprint 4)

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#222]

**Comment by saralavanip** [comment]
Please find the reference issues below based on discussion with @brylie  .

https://github.com/Digipalvelutehdas/dipor-dashboard/issues/238  
 https://github.com/Digipalvelutehdas/dipor-dashboard/issues/239

**Comment by saralavanip** [comment]
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/242

**Comment by saralavanip** [comment]
Verified the resolved issues: 
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/168    
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/167

**Comment by bajiat** [comment]
@saralavanip Should we close this issue?

**Comment by bajiat** [comment]
@saralavanip Closing the issue since you have already moved on to sprint 5 deployment testing.
