### ISSUE TITLE
Add user management UI

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#223]
Create a user interface to manage platform users. Include the ability to toggle "superuser" role for individual user(s).

# Definition of done
- [x] User administration view exists
- [x] User administration view shows list of existing users
- [ ] User administration view allows toggling of *admin* role on a single user

**Comment by jykae** [comment]
Trying again with accounts-admin-ui, got issue fixed https://github.com/apinf/meteor-accounts-admin-ui-bootstrap-3/issues/1

Making new PR.

**Comment by jykae** [comment]
Awesome, got it working here:

<img width="1157" alt="nayttokuva 2016-04-20 kello 15 48 47" src="https://cloud.githubusercontent.com/assets/293452/14675018/8aa5e23a-070f-11e6-8ec5-a09a010e3499.png">

**Comment by brylie** [comment]
Right on! :smiley:

**Comment by jykae** [comment]
@brylie What do you think, is it fine to have that "toggling" admin role like it is provided by accounts-admin-ui package?

**Comment by brylie** [comment]
Yeah, that is fine.
