### ISSUE TITLE
Determine how to handle uppercase letters in user and repository names

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#225]
Github usernames are case-insensetive. However, when returning data, the username or repository seems to retain the case. In Dipor, users can enter the username and repository in any case, so the strings may not match. Determine how to handle uppercase letters in Github usernames and repositories.

**Comment by brylie** [comment]
@frenchbread will you please co-pilot this task.

**Comment by frenchbread** [comment]
@brylie Sure.

**Comment by frenchbread** [comment]
Basically we have two approaches here:
- Do not use `toLowercase()` conversion and let repo names letter be in a case they originally are
- Convert all names to lowercase and provide regex option to be able to fetch documents with no matter of case. E.g.: 
```js
name: {
    $regex: repoName,
    $options: 'i' // case-insensitive option
}
```

**Comment by brylie** [comment]
@frenchbread where are we using this `$regex`? Is this in the collection query?

**Comment by frenchbread** [comment]
@brylie Yes. I think we sholud do it for each use of mongodb call where repo name or username is used for filtering.
For example:
```js
// Check if issue has already been added
const issueExists = GithubIssues.findOne({
    repository: {
        $regex: repo,
        $options: 'i'
    },
    user: {
        $regex: user,
        $options: 'i'
    }
});
```

**Comment by brylie** [comment]
OK, good idea. I will create a working branch now.

**Comment by brylie** [comment]
@frenchbread will you review PR #240?
