### ISSUE TITLE
Ensure the `id` field is unique for Github issue data

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#226]
Each Github issue seems to have a unique `id` field. Ensure that our collection enforces uniqueness for the `id` field, to prevent duplicate data.

# Definition of done
- [ ] `id` field in [`GithubIssues` collection](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/integrations/github/issues/collection/collection.js#L1) has rule to ensure uniqueness

# References
- Github issues [collection index](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/integrations/github/issues/collection/collection.js#L5-L10)
- Github commits [collection index with ensure unique](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/integrations/github/commits/collection/collection.js#L7)
- EnsureIndex {Mongo docs}(https://docs.mongodb.org/v2.6/reference/method/db.collection.ensureIndex/)

**Comment by jykae** [comment]
Side note: Meteor uses quite old Mongo version, newest is 3.2 and we have 2.6.7.
