### ISSUE TITLE
Create button for manual sync of github data

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/dipor-dashboard#234]
User should be able to obtain realtime data any time s.he wishes to apart from the everyday export activity.

Provide UI (button) 
Also keep a text log to include export paramters and status ( required to detect errors if export is unsuccessful)

# Definition of done
Choose at least one of these tasks:

- [x] Button exists for manual syncing of Github data for a given data source
  - Issues
  - Commits
- [x] Button exists for manual syncing of Github data for a given service
- [x] When clicking "sync" button, all relevant Github data is fetched

**Comment by brylie** [comment]
@frenchbread, @Alapan, or @elnzv, will you please consider taking this issue?

**Comment by Alapan** [comment]
@brylie I can take this issue.

**Comment by brylie** [comment]
Thanks @Alapan :-)

**Comment by Alapan** [comment]
Is there any specific page/view on which this button has to be located?

**Comment by brylie** [comment]
@alapan or @Nazarah, where would you recommend placing the UI button?

**Comment by Nazarah** [comment]
It should be added to pages, where you can glance service level statuses.

Cases:
1. For example, based on the agreed upon wireframes, if we decide to incorporate a summary of services and their status in department page, then there should be a Manual Sync Button
2. In service pages, there should be one
3. If we decide to create a customizable home page for logged in users, there should be as well.
Considering user has the option to add favorite services in his homepages, a sync button should be available for all services.
OR
if there is some way to trigger sync for all services by a single button, that would be better even.

**Comment by brylie** [comment]
@Nazarah what do you mean by "agreed upon wireframes"? Which wireframes? Which parts of the wireframes?

**Comment by Nazarah** [comment]
I will upload 2 versions of department view today in Github.
There I have left provisions for showing brief summary of projects.
You can see there.
Agreed upon means that if we can organize a meeting, we can decide upon which design to implement or if to produce a 3rd one combined with features from both.

**Comment by Alapan** [comment]
Does it make sense to have a button for each source in the integrations chart on the service pafe? That way the user knows for which source the issues and commits are being synced.

**Comment by brylie** [comment]
@Alapan that is a good idea. Try to show the button only for service owners. I can help write a template helper to check whether the current user is a service owner.

**Comment by Alapan** [comment]
@brylie The `serviceIntegrations` template, having the 'Sync' button I added, is being called by the [details HTML page](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/services/client/single/detail/detail.html). There, a check is being made to determine if the current user is the owner or not `{{# if service.currentUserIsOwner }}`. That is why I have not added any checks myself right now.

**Comment by brylie** [comment]
OK, I understand why we don't need to duplicate the check.
