### ISSUE TITLE
Allow editing of Github sources on Service view

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#239]
An end-user may need to edit details about a Github source, e.g. to correct a spelling mistake. Add an 'edit' button next to each Github source, allowing an end-user to change Github details.

As an administrator or service owner I need to be able to edit Github source details so that I can correct error or change details.

# Definition of done
- [x] Edit button exists next to Github repository name.
- [x] When clicking the edit button, user is represented with an edit form.
- [x] When clicking save, 
  - [x] the data source is updated.
  - [x] the sync function(s) are run. (Edit by bajiat 2016-05-13: This is optional)
- [x] Allow deleting a repository from the services view (Edit by bajiat 2016-05-13)

**Comment by Nazarah** [comment]
How about considering that when you are adding the service for the very first time, you need to be sure of the gituhub source and repository source.

**Comment by bajiat** [comment]
@frenchbread Last point about deletion should work so that you check that no other service is using the same repository. If another service has the same repository, delete it only from the view. If only this service uses the repository, delete it from the collection(s) as well. To be checked: Do you need to delete the syncing as well?

**Comment by brylie** [comment]
@frenchbread what is the status of this task?

**Comment by bajiat** [comment]
@frenchbread Would you be able to start and finish this task before the end of sprint / release?

**Comment by frenchbread** [comment]
@bajiat yes. I will finish it by Friday.

**Comment by frenchbread** [comment]
@bajiat I will add functionality that cleans up unneeded synced data. @elnzv is working on this feature actually so I could reuse it when service has been edited

**Comment by bajiat** [comment]
@frenchbread Check the edited definition of done.

**Comment by frenchbread** [comment]
Got "sync" functionality working.. Thanks @brylie.

**Comment by frenchbread** [comment]
Looks like:
![screen shot 2016-05-13 at 15 08 59](https://cloud.githubusercontent.com/assets/2122679/15247405/aeb59e4e-191c-11e6-9517-2d94755d6a20.png)
