### ISSUE TITLE
Not able to add new source

### ISSUE THREAD

**Issue by nnn** [Digipalvelutehdas/dipor-dashboard#260]
# Short bug title
Not able to add new source

# Steps to reproduce
1. Go to organization -> department - > service
2. Add Source -> Choose github -> Enter username and repo name -> Add
3. Without reloading a page repeat step 2

# Observed behavior
Form never submits 
Getting this message in server console:
```
Error inside the Async.runSync: Github is not defined
```

# Environment
- Google Chrome Version 50.0.2661.75
- Windows 10

**Comment by frenchbread** [comment]
Try pulling changes from updated `develop` branch.

**Comment by elnzv** [comment]
@frenchbread, checking this with latest develop. Bug still exists.
