### ISSUE TITLE
Add user information to indicate currently logged in user

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/dipor-dashboard#276]
Add the name of the logged-in user in master layout either on top of tab bar. i.e. the navigation menu. 
Refer to
 ![wireframe](https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Organizational%20View%20(Registered%20Users)/V1/OrganizationalView1.1.png)

As a user I want to be recognised, when I'm logged in so that I can easily see who I'm logged in as.

# Definition of done
- [ ] Name of logged-in user (if available) is displayed in navigation menu. If the user has not given a name, show the email.

**Comment by brylie** [comment]
@Nazarah will you please add a link to your wireframe for this enhancement?

**Comment by jykae** [comment]
interested on this one

**Comment by Nazarah** [comment]
Link of the picture:
https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Settinngs/5.%20Access%20and%20PrviledgesAnyUserDefault.png

Link of Balsamiq Mockup:
https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/docs/Design/LoFiPNGs/Settinngs/5.%20Access%20and%20PrviledgesAnyUserDefault.bmml
