### ISSUE TITLE
Add and remove department administrators

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#286]
As a superuser, organization administrator or department administrator, I want to add and remove department administrators.

# Definition of done
- [ ] Superuser can add and remove department administrators globally.
- [ ] Organization administrators can add and remove department administrators only inside their organization.
- [ ] Department administrators can add and remove department administrators only inside their department.

**Comment by jykae** [comment]
interested

**Comment by Nazarah** [comment]
Beside added user names, there should be remove button

**Comment by Nazarah** [comment]
Also include warning POP up "Are you sure you want to remove <firstname><lastname> as Admin?"

**Comment by elnzv** [comment]
Just as an idea, we can add a label showing if user is a superuser, instead of an additional  block showing it.

**Comment by Nazarah** [comment]
^ above idea sounds good.

**Comment by brylie** [comment]
Alright. In that case, we need to add a toggle field to the "add department member" form, and possibly create an "edit organization member" form as well.
