### ISSUE TITLE
Include organization catalog to landing page

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#289]
All organizations catalog can be viewed in the landing page. Include counts of services by status for each organization.

# Wireframe(s)
![wireframe](https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Misc%20GUIs/Organization%20Texts%20(Landing%20Page).png)

# Definition of done
- [ ] All organization catalog views is included in landing page.

**Comment by Nazarah** [comment]
consider the search based on services.
available services should be made public by respective PO

**Comment by Nazarah** [comment]
wish to work on the texts and I18N things

**Comment by elnzv** [comment]
@Nazarah, any suggestions on landing page text?

**Comment by Nazarah** [comment]
Will be adding wireframe link as soon as pull request gets accepted.

**Comment by brylie** [comment]
@Nazarah PR is merged.

**Comment by Nazarah** [comment]
Picture: 
https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Misc%20GUIs/Organization%20Texts%20(Landing%20Page).png

Mockup:
https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Misc%20GUIs/Organization%20Texts%20(Landing%20Page).bmml

**Comment by brylie** [comment]
@elnzv and @Nazarah, the above wireframe is now included in the task definition.
