### ISSUE TITLE
Visualization for count closed and open issues

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#291]
For a given repository, display counts open vs. closed issues as a visualization.

Refer to #7 in Github viewer: ![screenshot](https://cloud.githubusercontent.com/assets/293452/14116264/80d4dd58-f5e7-11e5-852a-5318db9e64c5.png)

# Definition of done
- [ ] Service page displays current count for open and closed issues in each data source. Optionally, display "doughnut" or bar chart.

**Comment by jykae** [comment]
interested, would be good follow up

**Comment by Nazarah** [comment]
Should be for repository

**Comment by Nazarah** [comment]
can you consider timing option to view show this?

**Comment by jykae** [comment]
@Nazarah what you mean with timing option? 
We have 2 different charts, open & closed overall and  @brylie 's time series based open & closed issues chart.

**Comment by jykae** [comment]
Used NVD3 as requested by @brylie instead of previous Chart.js lib

**Comment by Nazarah** [comment]
@jykae : I was considering if issues open and closed can be shown with respect to time.
But if the charts are for general information. It is fine.

**Comment by Nazarah** [comment]
Also suggesting the ideas to show the open and close issues as cards/widgets.
