### ISSUE TITLE
Sprint 5 deployment testing

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#293]
Go to [Dipor deployment](dashboard.digipalvelutehdas.fi) for release based on sprint 5 and test the available views. Check the sprint 5 release note to see what is new and changed.

Definition of done
---
* [x] Report any problems as issues
  * [x] Describe the test to reproduce the problem
  * [x] List all created issues as a comment to this task

**Comment by bajiat** [comment]
@saralavanip Release will probably take place only tomorrow. We will add a comment here when the release and deployment have been made.

**Comment by jykae** [comment]
@saralavanip Version 0.5.0 running after couple of issues.

**Comment by saralavanip** [comment]
Testing in progress.

**Comment by bajiat** [comment]
@saralavanip How is this task proceeding? Since this is the last sprint I'm wondering whether we should continue with testing the develop branch. That would mean setting up development environment for you. You can find instructions in the [Readme](https://github.com/Digipalvelutehdas/dipor-dashboard). How does that sound to you?

**Comment by saralavanip** [comment]
@bajiat , OK, I'll continue testing with develop branch. Please find the reference issues reported:  

https://github.com/Digipalvelutehdas/dipor-dashboard/issues/318  
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/322  
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/317

**Comment by saralavanip** [comment]
Please find the reference issues reported:     
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/354  
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/355   
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/356   
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/357   
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/358  
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/363    
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/364
