### ISSUE TITLE
Fix duplicate text of Service status

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#295]
If PO or superuser edits the service status and saves the change, the text for status gets duplicated, e.g. developmentdevelopment.

# Definition of done
- [ ] When saving updated service status, status text appears only once in service header.

**Comment by saralavanip** [comment]
This issue was reproducible in v0.5.0  and please find the screenshot below: 

![edit_service_status_replicates](https://cloud.githubusercontent.com/assets/13309358/15012554/3e1ce03c-1202-11e6-9929-9c7f4d0ee5c8.png)
