### ISSUE TITLE
Enhance view permissions

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#297]
Make sure that all users (anonymous, logged-in, logged-in organization members and logged-in department members can view and navigate to public services.

Make sure that only logged-in organization and department members can view and navigate to the private services per organization.

Blocked by #192.

# Definition of done
- [x] On organization page, departments block is visible to all users.
- [x] On department page, services block is available to all users.
  - [x] public services visible to all users.
  - [x] private services are visible only to    
    - [x] department
    - [x] organization members.

Co-pilot: @Nazarah

**Comment by Nazarah** [comment]
Interested with wireframes

**Comment by jykae** [comment]
Waiting for public/private toggle from #192

**Comment by brylie** [comment]
Double checked permissions from definition of done. They match the requirements, as of Sprint 6.
