### ISSUE TITLE
Add services table, or other listing, to organization page

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#304]
The 'organization' page currently contains a placeholder for related services. Create a collection helper and table to display all services related to a given organization.

**Comment by Nazarah** [comment]
Version 1:
picture: https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Department%20View%20(Registered%20Users)/V1/DepartmentView1.1.png

mockup: https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Department%20View%20(Registered%20Users)/V1/DepartmentView1.1.bmml

Version 2:
picture: https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Department%20View%20(Registered%20Users)/V2/DepartmentView2.2.png

mockup: https://raw.githubusercontent.com/Digipalvelutehdas/dipor-dashboard/develop/docs/Design/LoFiPNGs/Department%20View%20(Registered%20Users)/V2/DepartmentView2.2.bmml

**Comment by Nazarah** [comment]
Just adding the reference to the appropriate wireframes
(2 versions)

Version1:
https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/docs/Design/LoFiPNGs/Organizational%20View%20(Registered%20Users)/V1/OrganizationalView1.1.png

https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/docs/Design/LoFiPNGs/Organizational%20View%20(Registered%20Users)/V1/OrganizationalView1.2%20(2).png

Version2:
https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/docs/Design/LoFiPNGs/Organizational%20View%20(Registered%20Users)/V2/OrganizationalView2.1.png


https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/docs/Design/LoFiPNGs/Organizational%20View%20(Registered%20Users)/V2/OrganizationalView2.2%20(2).png
