### ISSUE TITLE
Heuristic evaluation of current platform

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#310]
Evaluate the current deployment based on [heuristic article]. Please include details about the chosen heuristic(s), and how they are relevant to the project.

**Comment by bajiat** [comment]
@nazarah Is there a report for the evaluation or a list of findings?

**Comment by Nazarah** [comment]
It is a list of findings along with which heuristics were violated and what is the severity rate.
the heuristics and the severity  rates are also described in a separate tab in the same excell sheet.
