### ISSUE TITLE
ensureIndex throwing error in production database

### ISSUE THREAD

**Issue by jykae** [Digipalvelutehdas/dipor-dashboard#316]
We have MongoDB 2.6.7 in development and in production 3.2.6 (mupx probably gets the latest). ensureIndex is deprecated and dropped out in 3.2. Experiment if new createIndex would work.

Reference: https://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/

**Comment by brylie** [comment]
> ensureIndex is deprecated and dropped out in 3.2

How do we verify that statement? 

The [MongoDB 3.2 documentation](https://docs.mongodb.com/v3.2/reference/method/db.collection.ensureIndex/) only says the following:

> Deprecated since version 3.0.0: db.collection.ensureIndex() is now an alias for db.collection.createIndex().

**Comment by jykae** [comment]
@brylie From collection2 tests:
https://github.com/aldeed/meteor-collection2/blob/53aa3a48ab0a1548be780ffafbccb30e07e9493f/tests/collections.js

We should most likely to use try catch, try to drop existing index, and then create index with "_ensureIndex".
