### ISSUE TITLE
Inconsistency in no. of issue between dipor visualization and original github repository

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/dipor-dashboard#332]
> Use this section for a bug report

# Short bug title
There is mismatch in no. of open and closed issues between dipor dashboard visualization and original github repository

# Steps to reproduce

1. https://dashboard.digipalvelutehdas.fi
2. go to Organizations   Nazia's Test Organization   Digipalvelutehdas   Dipor Dashboard
3. Hover on donut chart for issues
4. monitor no. of open and closed issues.
5. go to original repository in github
6. click on issue tab

# Observed behavior
No. of issues (both open and closed) mismatches in both places

# Expected behavior
The number should be consistent in both place

# Environment

- chrome
- windows 8
**Note:** Some of the above details will be added during the discussion and testing process.

**Comment by brylie** [comment]
Good catch, and excellent bug reporting @Nazarah! :-)
