### ISSUE TITLE
Inline editing text keeps doubling

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#337]
We have had struggles with the reactive inline editing of text. Check all templates with inline editing capabilities to ensure the text is not duplicated on screen when saving.

Specifically:

- [x] Organization page
- [x] Department page
- [x] Service page

**Comment by bajiat** [comment]
@frenchbread Would you have time for one more task this sprint? This bug is probably a regression and you know the inline editing well.

**Comment by bajiat** [comment]
@jykae will be taking this task, since his other task is blocked, but maybe @frenchbread could co-pilot if help is needed.

**Comment by brylie** [comment]
@jykae thanks for taking this task.

**Comment by frenchbread** [comment]
I'll co-pilot. 😄

**Comment by jykae** [comment]
great, @frenchbread can you point line how to that doubling has been fixed earlier?

**Comment by frenchbread** [comment]
@jykae I'll take a look how this has been fixed earlier. Do not really remember.

**Comment by jykae** [comment]
Ok, I remembered that we had this sort of doubling earlier also, trying check and compare what is missing.. Point out if you find it first.

**Comment by frenchbread** [comment]
it seems that medium-editor option did the thing then. ([Link](https://github.com/Digipalvelutehdas/dipor-dashboard/pull/61#issuecomment-191735484))

**Comment by frenchbread** [comment]
Not sure it that approach going to work with select-box widget

**Comment by jykae** [comment]
Yep, this is something different.. Header text editing works correct if I don't touch to select-box before editing that. Tried adding class "editable" also for service status. Did not have effect though.. Looking this through with debugger.

**Comment by jykae** [comment]
This is some sort of timing issue with reactivity.. I tried couple of things and debugged with debugger and console.logs. Can you try this @frenchbread ? Can't find the issue.

**Comment by jykae** [comment]
Only Service page where we have select-box has this issue.

**Comment by jykae** [comment]
#295 is subtask of this one

**Comment by jykae** [comment]
Got it fixed, though quite a DOM hack..

**Comment by bajiat** [comment]
@jykae @brylie Note also the bug report created by @saralavanip today: #356 Edit and save organization 'Title' gets duplicated text
