### ISSUE TITLE
Add delete functionality for removing organizations, departments and services

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#338]
As a superuser I want to be able to delete organizations, departments or services so that I can remove obsolete or erroneous units.

## Definition of done
- [ ] A superuser can delete organizations, departments or services.
  - [ ]  If an organization is deleted, there will a cascading delete, where relevant departments, services and integrations (Github repos) are removed (departments belonging to that organization, services linked to departments that are being deleted, integrations linked to services to be removed).
    - [ ] The user gets a warning about deleting also N departments, N services and N integrations.
  - [ ] If a department is deleted, there will be a cascading delete for services and integrations (services linked to the department, integrations linked to the services to be deleted.)
    - [ ] The user gets a warning about deleting also N services and N integrations.
  - [ ] If a service is deleted, also relevant integration(s) are removed.

Note that 
 - [ ] Github repositories can potentially belong to more than one service. They can only be removed after checking that they are not linked to a service that remains on the portal. This applies to all cascading delete cases above.

**Comment by bajiat** [comment]
@elnzv Will you be able to finish this task for this sprint?

**Comment by elnzv** [comment]
Yes, I am more than half way there. Doing my best to have it done today.

On Fri, 13 May 2016, 10:26 Taija Björklund, <notifications@github.com>
wrote:

> @elnzv <https://github.com/elnzv> Will you be able to finish this task
> for this sprint?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Digipalvelutehdas/dipor-dashboard/issues/338#issuecomment-218970648>
>
-- 

Illya Nizyev ~ www.nzv.nz
