### ISSUE TITLE
Remove Sync button from Service view

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#361]
Definition of done
- [ ] Remove Sync button and column to make more room for the charts.
  - [ ] Indicate the time of the last sync below the last row of table.

**Comment by bajiat** [comment]
@elnzv Since we are running out of time, we decided to move the task #210 back to backlog. The sync button must be removed, so we created this task and assigned it to you.

**Comment by saralavanip** [comment]
Verified in latest deployed version 0.6.0 https://dashboard.digipalvelutehdas.fi
