### ISSUE TITLE
Layout breaks when editing organization

### ISSUE THREAD

**Issue by frenchbread** [Digipalvelutehdas/dipor-dashboard#367]
# Layout issue
After replacing medium editor with x-editable and when editing organization, description field is misplaced.

![screen shot 2016-05-16 at 10 46 23](https://cloud.githubusercontent.com/assets/2122679/15283507/cb9d4f28-1b53-11e6-812e-9b6e39147f38.png)

# Steps to reproduce

1. Create organiaztion
2. Navigate to single organization page
3. Click edit button.
4. Click on description field. 
5. Description field is misplaces

# Environment
- Google Chrome Version 52.0.2738.0 canary (64-bit)
- MacOSX 10.11.4

**Note:** Same issue happens when editing department or service (field is not misplaced but has "default" height and width). The possible solution is to add needed styles to "description" textarea field.

**Comment by jykae** [comment]
@frenchbread Can reproduce only in organization page.

**Comment by jykae** [comment]
In Organization page description is in the same Bootstrap "row". Fixing..

Can you verify @frenchbread that this is surely happening on department / service views as well?

**Comment by frenchbread** [comment]
@jykae Update the issue description. Actually the fields are not misplaced on departemnt and service pages but have default width and height.

**Comment by jykae** [comment]
@frenchbread what you mean by "default" width/height? Editable field sizes when on edit mode?

**Comment by saralavanip** [comment]
Verified the resolved issue on version 0.6.0 https://dashboard.digipalvelutehdas.fi
