### ISSUE TITLE
Integrations table width problem in IE10

### ISSUE THREAD

**Issue by elnzv** [Digipalvelutehdas/dipor-dashboard#378]
Integrations table width is bigger than should be in Internet Explorer 10. 
Part of the table is not showing properly.
Attaching screenshot.

![ie_bug](https://cloud.githubusercontent.com/assets/7489044/15289624/2701c772-1b7c-11e6-963a-7899b88ef3a8.png)

**Comment by saralavanip** [comment]
Verified  on version 0.6.0 https://dashboard.digipalvelutehdas.fi
