### ISSUE TITLE
Create a modal view for adding an organization

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#49]
Create a view that all inserting a new organization into the portal.

Definition of done
---
* [ ] Modal dialog package added to project.
* [ ] Autoform package added to project.
* [ ] Add form template included in project.
* [ ] Add organization field contains name and description fields.
* [ ] When inserting an organization, current user id is added to organization admin id fields organization document.
* [ ] User gets assigned an administrator role for the particular organization.

**Comment by frenchbread** [comment]
interested
