### ISSUE TITLE
Create initial Swagger json with Organization API details

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#5]
_From @bajiat on February 19, 2016 12:22_

Use a tool to create the Swagger file for Organization REST endpoints.

Definition of done
---
* [ ] Swagger file exists in project.
* [ ] Swagger file contains general description of API.
* [ ] Swagger file contains specific details for each API endpoint.
* [ ] Swagger file passes validation.
* [ ] Swagger file is published and accessible via URL route.

_Copied from original issue: Dipor/platform#15_

**Comment by kyyberi** [comment]
And contains data models as we know them at that point
