### ISSUE TITLE
Create a modal view for adding a department

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#50]
Create a view that all inserting a new department into the portal.

Definition of done
---
* [x] Modal dialog package added to project, if not already added.
* [x] Autoform package added to project,  if not already added.
* [x] Add form template included in project.
* [x] Add department field contains name and description fields.
* [x] When inserting a department, current user id is added to department administrator id fields.
* [x] When inserting a department, organization id is added to department organization id field.
* [ ] User gets assigned an administrator role for the particular department.

**Comment by bajiat** [comment]
@frenchbread Could you take this task? It is similar to the one you were interested in (modal view for adding department).

**Comment by frenchbread** [comment]
@bajiat self-assigned
