### ISSUE TITLE
Add inline editing to single department view

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#51]
Add inline editing functionality to single department view. 

Definition of done
---
* [ ] Edit button for organization view exists.
* [ ] Clicking edit button enables inline editing for page elements
* [ ] Clicking save button saves changes to database.
* [ ] Cancel button disables edit more
* [ ] Only edit button or save and cancel buttons are available at any given time.
* [ ] Edit and save / cancel buttons are available only for administrators.

**Comment by frenchbread** [comment]
interested

**Comment by bajiat** [comment]
@frenchbread Assigned to you. Can you please estimate?

**Comment by frenchbread** [comment]
@bajiat Time-estimations are in [2016-03-07-Sprint-02-Planning.md](https://github.com/Digipalvelutehdas/dipor-dashboard/commit/3ec70f0fda29b9119148504f6fd5d87ca0f737ef) file.

**Comment by frenchbread** [comment]
Depends on #45 and #46.

**Comment by bajiat** [comment]
@frenchbread Thanks for estimating. I added your estimations to the tasks on the sprint board. For task #53 you had estimated 15h, but since that is not available in Waffle, I marked it as 13h.
