### ISSUE TITLE
Create a department member management view

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#53]
Create an user interface to add department members from existing users. Allow user role to be assigned at department level.

Definition of done
---
* [ ] Department member management template exists.
* [ ] Template includes field for entering email for the purpose of searching users.
* [ ] Template includes list of current department members.
* [ ] Template allows roles to be assigned to current department members.
  * [ ] When selecting a new department member, user id is stored in department member ids field.

**Comment by bajiat** [comment]
@frenchbread Would you be interested in this task? You can follow the model from #7 by @brylie

**Comment by frenchbread** [comment]
Depends on #45
