### ISSUE TITLE
Create portal logo

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#56]
Create Dipor portal logo using Roboto font bold. All characters in logo should be upper case.

Definition of done
---
* [ ] Logo exists.
* [ ] Logo has been added to public folder in code repository.
* [ ] Logo has been added to main layout.

**Comment by elnzv** [comment]
@kyyberi, is it something asked for? and which one of these?

![dipor_logo](https://cloud.githubusercontent.com/assets/7489044/13522765/25a0e5a4-e1fa-11e5-87c0-bfddd74f2ccc.png)
![digipalvelutehdas_logo](https://cloud.githubusercontent.com/assets/7489044/13522766/27a35026-e1fa-11e5-9c3f-7df5f049dbcb.png)

**Comment by elnzv** [comment]
"In real life":
![screencapture-localhost-3000-1457083285052](https://cloud.githubusercontent.com/assets/7489044/13522994/6ec13030-e1fb-11e5-96a2-21d27fb4e565.png)

**Comment by kyyberi** [comment]
The small example case looks good.

**Comment by elnzv** [comment]
@kyyberi, which one of two closes this issue? and where should I upload the logo?

**Comment by kyyberi** [comment]
Upload to github repo so that it goes to dipor server in deployment. DIPOR is the one.
