### ISSUE TITLE
Deploy sprint 1 demo to VM

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#62]
OpenStack environment.

Definition of done
---
* [x] Subdomain is created.
* [x] VM is created.
* [x] Dependencies are installed via MupX.
* [x] MupX script exists in secure, shared location.
* [x] Prototype has been deployed to virtual machine using MupX.
* [x] Customer has been notified about availability.

**Comment by jykae** [comment]
Interested in this one.

**Comment by bajiat** [comment]
@jykae You can find the release here: https://github.com/Digipalvelutehdas/dipor-dashboard/releases/tag/0.1.0

**Comment by jykae** [comment]
dashboard.digipalvelutehdas.fi is up, customer has been notified

I will put deployment files to shared location.

**Comment by jykae** [comment]
I will also generate Let's Encrypt SSL certificate as a part of this task. Customer seems to like SSL Everywhere.

**Comment by jykae** [comment]
dashboard.digipalvelutehdas.fi has now also SSL certificate in addition to things listed.
