### ISSUE TITLE
Auto-generate API documentation file

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#66]
Refer to [Meteor SimpleREST issue #93](https://github.com/stubailo/meteor-rest/issues/93)

Definition of done
---
* [x] Review the issue 
* [x] Get an uderstanding of what code needs to be written
* [x] Fork or create a new package
* [x] Review Swagger spec for required fields for producing a Swagger file
* [x] Implement minimum required Swagger fields in JSON format
  * [x] When a user visits Swagger endpoint, they receive valid Swagger JSON
* [ ] Open PR on Meteor Simple REST

**Comment by jykae** [comment]
I could be co-pilot for @brylie or someone who takes this. Closely related to REST task.

**Comment by jykae** [comment]
@brylie I commented to the original issue, trying to get understanding how I should do this.

**Comment by jykae** [comment]
I think we could keep discussion in the original issue. How about forking under Apinf organization, working there and then contributing back to meteor-rest? Forks can be compared, so I think I would be able to do PR that way.

**Comment by jykae** [comment]
Forked under Apinf organization: https://github.com/apinf/meteor-rest 
I could make also the other small improvements I wrote down in issue #68

**Comment by jykae** [comment]
There is nice initial test set for meteor-rest packages. I think I need to make changes only to "packages/rest" and "packages/json-routes".

![simpletest](https://cloud.githubusercontent.com/assets/293452/13603965/454e5eca-e549-11e5-9634-26b514a313d6.png)

**Comment by jykae** [comment]
There is minimal Petstore Swagger that I could use as reference: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-minimal.json

**Comment by jykae** [comment]
Swagger parser/validator for checking produced output: http://bigstickcarpet.com/swagger-parser/www/index.html

**Comment by jykae** [comment]
I think I try to make separate plugin package as @brylie suggested in the original issue, it would be easier to switch to another format.

**Comment by jykae** [comment]
I put this on hold if Restivus would be better alternative for us #87

Both packages use json-routes, but Restivus might be more mature and customizable. Also stubailo recommended to use that one if we want more RESTful approach.
simple:rest authentication is also pretty much work in progress.

**Comment by jykae** [comment]
Continuing, looking how this would fit with Restivus.

**Comment by jykae** [comment]
Swagger route added.
Main meta can be defined in Restivus configuration:

![swagger](https://cloud.githubusercontent.com/assets/293452/13701826/fe37b0e4-e792-11e5-9d51-f119da53d765.png)

**Comment by brylie** [comment]
@jykae great work!

**Comment by jykae** [comment]
Package code: https://github.com/apinf/restivus-swagger

I will make PR about Restivus configuration, and route meta configurations, when I am closer.

**Comment by jykae** [comment]
PR opened.
Package published in Atmosphere, https://atmospherejs.com/apinf/restivus-swagger

Generated swagger.json is minimum viable valid swagger.json

![validswagger](https://cloud.githubusercontent.com/assets/293452/13752249/867a1dc2-ea16-11e5-8e49-3440d6ff6dbc.png)
