### ISSUE TITLE
Set up unit testing framework

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#67]
Following the example from Apinf, set up unit testing framework for Dipor. Add the required packages and write the example test(s) for our organization feature.

Definition of done
---
* [x] Testing packages have been added to project.
* [x] Organization feature contains at least one unit test.
* [x] Read.me contains instruction on how to run unit tests.

**Comment by bajiat** [comment]
@alapan @ashakunt Is this a suitable task for Alapan for this sprint?

**Comment by Alapan** [comment]
I wrote some tests and ran them successfully. However, when trying to push my branch, I got a Permission Denied error.
