### ISSUE TITLE
REST API improvements

### ISSUE THREAD

**Issue by jykae** [Digipalvelutehdas/dipor-dashboard#68]
Sub-tasks:

* [x] Define authentication method for REST API, token based authentication preferred
* [x] Expose only relevant API endpoints
* [x] Find out how to customize API endpoint routes, would be good to have everything under "/api" -route

**Comment by kyyberi** [comment]
Version must be in path "/api/v1/organisations/{id}"

**Comment by jykae** [comment]
We are probably switching to Restivus for maturity and customizability, https://github.com/kahmali/meteor-restivus

Supports also versioning like in guidelines.
