### ISSUE TITLE
Explore plotly.js

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#70]
plotly.js is a charting library. Check out the possibilities and create a demo to display some charts.

Definition of done
---
* [ ] New Meteor project has been created.
* [ ] plotly library is added to project.
* [ ] Sample data has been downloaded or created.
* [ ] Application displays two different chart types on frontpage.

**Comment by bajiat** [comment]
@frenchbread Would you be interested in this? Only if you have time, other tasks have higher priority.

**Comment by frenchbread** [comment]
@bajiat Ok.

**Comment by bajiat** [comment]
Closing the issue, since we are planning to use Dimple.
