### ISSUE TITLE
Create Github integration example

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#71]
Study the Github APIs and select the most relevant data available through the API. Create a sample application that pulls data through the Github API.

**Note:** For this task, prioritize only public data, so that we do not have to work with authentication tokens at this point.

Definition of done
---

* [x] New Meteor demo project exists.
* [x] Optionally, Github integration package has been added to Meteor demo project.
* [x] Create a single front page.
* [x] Application demonstrates pulling data through API, e.g. repository titles, number of commits on its front page.
 
# Resources
Depending on the permissions necessary, try to collect at least the following information for a single Github project:

- Github API [repository commits](https://developer.github.com/v3/git/commits/)
- Github API [stargazers](https://developer.github.com/v3/activity/starring/)
- Github API [list issues for a repository](https://developer.github.com/v3/issues/#list-issues-for-a-repository)

The following library implements most/all of the Github API in JavaScript:

- [node-github](https://github.com/mikedeboer/node-github)

There exists example code for fetching and visualizing Github data:
- [Github visualizer](https://github.com/artzub/GitHubVisualizer)

**Comment by bajiat** [comment]
@alapan @ashakunt Is this something Alapan could work with?

**Comment by bajiat** [comment]
@ashakunt Any updates on this? Does @alapan have any interest or time for this? The delete task in the Apinf side has been quite large, so we understand this has not been high priority. We could also assign this to someone else.

**Comment by Alapan** [comment]
@bajiat I will start with this today, as soon as I finish making changes in the 2 PRs I created last week.

**Comment by ashakunt** [comment]
(y)

**Comment by ashakunt** [comment]
assigned to @Alapan

**Comment by bajiat** [comment]
@Alapan That's great!

**Comment by Alapan** [comment]
Project created with Github package, in progress.

**Comment by brylie** [comment]
Do you have a repository where we can follow? Feel free to add a repository under our Dipor organization.

**Comment by brylie** [comment]
@Alapan I have created a repository for the github-viewer project:
https://github.com/Dipor/github-viewer

Please commit your code and continue working there.

**Comment by Alapan** [comment]
I created a feature to view a list of open pull requests for a given user/organization and a repository. It is working now, but I could not push my branch as I don't have access to the repository yet - https://github.com/Dipor/github-viewer

**Comment by Alapan** [comment]
@brylie I tried to push my feature branch now, but it showed:

`remote: Permission to Dipor/github-viewer.git denied to Alapan.
fatal: unable to access 'https://github.com/Dipor/github-viewer.git/': The requested URL returned error: 403`

**Comment by brylie** [comment]
I have given you write permissions on the repository. Did you accept the invitation?

**Comment by brylie** [comment]
Try again now.

**Comment by Alapan** [comment]
Ok, yes, very sorry, I didn't see the invitation I had received. I have pushed the branch and will create the PR now.

**Comment by brylie** [comment]
@Alapan run the following command(s) from within your repository directory:

```
git remote add upstream https://github.com/Digipalvelutehdas/github-viewer.git
```

**Comment by Alapan** [comment]
@brylie I executed the command.

**Comment by brylie** [comment]
OK, one moment. I am figuring out the specifics. Basically, we need to remove references to the previous git repository, and replace them with the new location under Digipalvelutehdas:

```
$ git config --remove-section remote.origin
$ git remote add origin https://github.com/Digipalvelutehdas/github-viewer.git
```

**Comment by brylie** [comment]
Those commands should update your repository references properly.

**Comment by brylie** [comment]
Once you have the proper remote references, you should be able to push your changes.
