### ISSUE TITLE
Create organization collection and schema

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#9]
_From @bajiat on February 19, 2016 12:14_

Based on user requirement document, create organize collection and define organization schema with at least most relevant fields.

Definition of done
---
* [ ] Organization collection exists.
* [ ] List of organization collection fields exists in plain text in this issue.
* [ ] Schema exists for most relevant fields.
* [ ] Schema has been attached to collection.

# Fields
These will be the initial fields for the Organizations collection schema:
## `name` 
* type: String
* regExp: Unique ID

## `admin`
Depending on whether we anticipate supporting multiple administrators per organization, we will create one of the following:

* administratorId - single administrator ID
* administratorIds - array of one or more administrator IDs

# Related
See the requirement document for [details about this feature](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/master/docs/requirements.md#organization-view-registered-user-who-is-a-member-of-the-organization-in-question).

## Dependent issues
* #17
* #18
* #19 

_Copied from original issue: Dipor/platform#8_

**Comment by bajiat** [comment]
jykae interested

**Comment by brylie** [comment]
@kyyberi do we anticipating there being the possibility of multiple administrators for any organizations? 

* If so, we should consider storing an array of userIDs in the administrator field. 
* If not, a single user ID can be stored.

**Comment by brylie** [comment]
@kyyberi the specification says "Name of the organization administrator and a link to a profile" when describing the organization view. This implies there should be only one administrator per organization.

I just want to clarify this point, so that we can build out permissions, etc. based on the data type of this field.

**Comment by brylie** [comment]
@bajiat this is a relatively small task, since there seem to be only two initial fields. I will open a PR once we have clarity regarding the "administrator" field, so that we can continue in related tasks.

**Comment by kyyberi** [comment]
@brylie probably have to be 2 admins in org due to holidays and so. Good clarification

**Comment by brylie** [comment]
@kyyberi I have made the change allowing multiple administrators per organization.

**Comment by kyyberi** [comment]
Excellent
